import type { CategoryDTO, SubcategoryDTO } from '../types/categories'

export const categories: CategoryDTO[] = [
  { categoryId: '1', name: 'Laptopovi' },
  { categoryId: '2', name: 'Desktop računari' },
  { categoryId: '3', name: 'Monitori' },
  { categoryId: '4', name: 'Komponente' },
  { categoryId: '5', name: 'Periferije' },
  { categoryId: '6', name: 'Gaming oprema' },
  { categoryId: '7', name: 'Mrežna oprema' },
  { categoryId: '8', name: 'Štampači i skeneri' },
  { categoryId: '9', name: 'Softver' },
  { categoryId: '10', name: 'Telefoni i tableti' },
]

export const subcategories: SubcategoryDTO[] = [
  { subcategoryId: '1', categoryId: '1', name: 'Gaming laptopovi' },
  { subcategoryId: '2', categoryId: '1', name: 'Poslovni laptopovi' },
  { subcategoryId: '3', categoryId: '1', name: 'Ultrabukovi' },
  { subcategoryId: '4', categoryId: '2', name: 'Gaming desktop' },
  { subcategoryId: '5', categoryId: '2', name: 'Poslovni desktop' },
  { subcategoryId: '6', categoryId: '3', name: '4K monitori' },
  { subcategoryId: '7', categoryId: '3', name: 'Gaming monitori' },
  { subcategoryId: '8', categoryId: '3', name: 'Ultrawide monitori' },
  { subcategoryId: '9', categoryId: '4', name: 'Procesori' },
  { subcategoryId: '10', categoryId: '4', name: 'Grafičke kartice' },
  { subcategoryId: '11', categoryId: '4', name: 'RAM memorija' },
  { subcategoryId: '12', categoryId: '4', name: 'Matične ploče' },
  { subcategoryId: '13', categoryId: '5', name: 'Tastature' },
  { subcategoryId: '14', categoryId: '5', name: 'Miševi' },
  { subcategoryId: '15', categoryId: '5', name: 'Slušalice' },
  { subcategoryId: '16', categoryId: '6', name: 'Gaming stolice' },
  { subcategoryId: '17', categoryId: '6', name: 'Gaming kontroleri' },
  { subcategoryId: '18', categoryId: '7', name: 'Ruteri' },
  { subcategoryId: '19', categoryId: '7', name: 'Svičevi' },
  { subcategoryId: '20', categoryId: '8', name: 'Laserski štampači' },
  { subcategoryId: '21', categoryId: '8', name: 'Inkjet štampači' },
  { subcategoryId: '22', categoryId: '9', name: 'Antivirusni softver' },
  { subcategoryId: '23', categoryId: '9', name: 'Kancelarijski paketi' },
  { subcategoryId: '24', categoryId: '10', name: 'Pametni telefoni' },
  { subcategoryId: '25', categoryId: '10', name: 'Tableti' },
]
